# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-tutorial-of-digital-identities
title: 量潮数字身份教程
author: 量潮科技
description: 量潮数字身份教程
# Jupyter Book Config
only_build_toc_files: true